In [1]:
import pandas as pd
!pip install Sastrawi
import Sastrawi
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import re

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 4.3 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [2]:
Raw_tweet = pd.read_csv("Raw_tweet.csv")
Raw_tweet.rename(columns={'tweetText': 'Tweet'}, inplace=True)
Raw_tweet['Sentimen']=""
display(Raw_tweet.head())

,id,Tweet,tweetURL,type,tweetAuthor,handle,geo,mentions,hashtags,replyCount,quoteCount,retweetCount,likeCount,views,bookmarkCount,createdAt,allMediaURL,videoURL,Sentimen
0,1878247059184365813,"Yuk, kita bikin tahun 2025 ini jadi milik kita...",https://x.com/psi_id/status/1878247059184365813,tweet,DPP PSI,@psi_id,Jakarta Capital Region,NaN,"#SemangatBaru,#Gaspol2025,#TahunBaru2025,#Sema...",32,0,0,7,327,0,1/12/2025 8:06,https://pbs.twimg.com/media/GhDfvB0aAAEIsoJ.jp...,NaN,
1,1878018603150385614,Mulai Tahun dengan Cerdas: Simak 5 Tips Resolu...,https://x.com/bartno/status/1878018603150385614,tweet,Ibnu Usmar,@bartno,Jakarta,NaN,"#TipsKeuangan,#Tabungan,#TahunBaru2025,#Resolu...",0,0,0,0,1,0,1/11/2025 16:58,NaN,NaN,
2,1878000424000901468,Kirim dipan dan meja rias Jakarta\nUntuk pemes...,https://x.com/BLORAJATI_1/status/1878000424000...,tweet,BLORA JATI PROJECT,@BLORAJATI_1,"Blora, Indonesia",NaN,"#dipan,#mejarias,#tahunbaru2025,#awaltahun",0,0,0,0,13,0,1/11/2025 15:46,https://pbs.twimg.com/ext_tw_video_thumb/18780...,https://video.twimg.com/ext_tw_video/187800013...,
3,1877987090409075119,Mari bersama-sama mewujudkan visi Rektor ITS d...,https://x.com/its_campus/status/18779870904090...,tweet,Institut Teknologi Sepuluh Nopember,@its_campus,"Kota Surabaya, Jawa Timur",NaN,"#ITSCampus,#ITSSurabaya,#ITSWorldClassUniversi...",0,0,0,1,172,0,1/11/2025 14:53,NaN,NaN,
4,1877703302994858207,"Terimakasih sebelumnya buat 2024, tahun itu ak...",https://x.com/sca_frisca/status/18777033029948...,tweet,Frisca A Maharti,@sca_frisca,Bandung,NaN,"#Bandung,#tahunbaru2025",0,0,0,0,6,0,1/10/2025 20:05,https://pbs.twimg.com/media/Gg7v7gjbAAAI4XQ.jpg,NaN,

##1. Data Understanding

In [8]:
#Cek tipe data
display(Raw_tweet.dtypes)

#Cek jumlah data
display(Raw_tweet.shape)

#Cek apakah ada baris kolom "Tweet" yang kosong
temp = (Raw_tweet["Tweet"].isnull().sum())
print(f"Jumlah baris kosong = {temp}")

#Cek apakah ada data yang terduplikasi
temp = (Raw_tweet.duplicated().sum())
print(f"Jumlah baris terduplikasi = {temp}")

id                int64
Tweet            object
tweetURL         object
type             object
tweetAuthor      object
handle           object
geo              object
mentions         object
hashtags         object
replyCount        int64
quoteCount        int64
retweetCount      int64
likeCount         int64
views             int64
bookmarkCount     int64
createdAt        object
allMediaURL      object
videoURL         object
Sentimen         object
dtype: object

(100, 19)

Jumlah baris kosong = 0
Jumlah baris terduplikasi = 0

##2. Text Prepocessing

In [4]:
#Hanya dibutuhkan kolom "Tweet" dan "Sentimen"
data = Raw_tweet[["Tweet","Sentimen"]]
display(data.head())

                                               Tweet Sentimen
0  Yuk, kita bikin tahun 2025 ini jadi milik kita...
1  Mulai Tahun dengan Cerdas: Simak 5 Tips Resolu...
2  Kirim dipan dan meja rias Jakarta\nUntuk pemes...
3  Mari bersama-sama mewujudkan visi Rektor ITS d...
4  Terimakasih sebelumnya buat 2024, tahun itu ak...

In [5]:
#Mengubah teks menjadi lower case
data.loc[:,'Tweet'] = data['Tweet'].str.lower()

#Normalisasi kata non-formal
norm = {'mw':'mau', 'dgn':'dengan', 'blm':'belum', 'bs':'bisa',
        '\n':'', ':':'', '#':' ', '?':'', ',':'',
        'banget':'sekali', 'tak':'tidak','meni':'sangat'}

def normalize(str_text):
  for i in norm:
    str_text = str_text.replace(i, norm[i])
  return str_text

data.loc[:,'Tweet'] = data['Tweet'].apply(normalize)

#Menghilangkan Stopword
stop_words = StopWordRemoverFactory().get_stop_words()
new_array = ArrayDictionary(stop_words)
stop_words_remover_new = StopWordRemover(new_array)

def Stopword(str_text):
  str_text = stop_words_remover_new.remove(str_text)
  return str_text

data.loc[:,'Tweet'] = data['Tweet'].apply(Stopword)

#Menghilangkan angka
data.replace('\d+', '', regex=True, inplace=True)

#Menghilangkan hyperlink karena banyak ditemukan pada dataset
def remove_link(text):
  return re.sub(r'http\S+', '', text)
data.loc[:,'Tweet'] = data['Tweet'].apply(remove_link)

#Menghilangkan emoticon
def remove_emoticons(text):
  emoticons_pattern = re.compile(u'([\U0001F600-\U0001F64F])|([\U0001F300-\U0001F5FF])|([\U0001F680-\U0001F6FF])|([\U0001F1E0-\U0001F1FF])', flags=re.UNICODE)
  return emoticons_pattern.sub(r'', text)
data.loc[:,'Tweet'] = data['Tweet'].apply(remove_emoticons)

display(data.head(10))
data.to_csv('Unstem_tweet.csv')

<ipython-input-5-faffcb71220e>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.replace('\d+', '', regex=True, inplace=True)

                                               Tweet Sentimen
0  yuk bikin tahun  jadi milik dalam mewujudkan i...
1  mulai tahun cerdas simak  tips resolusi keuang...
2  kirim dipan meja rias jakartauntuk pemesanan h...
3  bersama-sama mewujudkan visi rektor its membaw...
4  terimakasih sebelumnya buat  tahun aku banyak ...
5  maklumaninfo perkhidmatan perpustidakaan umska...
6  dukung asta cita presiden prabowopolsek tptm g...
7  electrizendimulai langkah kecil nyalakan perub...
8  menjenguk warga cibingbin blok wage rumahnya k...
9  jalan-jalan ulurujangan lupa payung abu-abusel...

In [6]:
#Tokenisasi, membagi kalimat menjadi token
tokenized = data['Tweet'].apply(lambda x: x.split())

#Stemming, mengubah menjadi kata dasar
def stemming(str_text):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  do = []
  for w in str_text:
    dt = stemmer.stem(w)
    do.append(dt)
  d_text = []
  d_text = ' '.join(do)
  print(d_text)
  return d_text

tokenized = tokenized.apply(stemming)

#Eksport tokens ke dalam file .csv untuk dilakukan sentimen analysis
tokenized.to_csv('Clean_tweet.csv')

yuk bikin tahun jadi milik dalam wujud impi sis n bro semangatbaru gaspol tahunbaru semangatsolidaritas solidaritastanpabatas indonesiamaju psi
mulai tahun cerdas simak tips resolusi uang tipskeuangan tabung tahunbaru resolusi
kirim dipan meja rias jakartauntuk mesan hubung kontidak bawah ya jl nasional blora-cepu watulumbung jiken kec jiken kab blora jawa tengah dipan mejarias tahunbaru awaltahun
sama wujud visi rektor its bawa kampus tuju masa depan lebih gemilang itscampus itssurabaya itsworldclassuniversity vivat pidatoawaltahun tahunbaru
terimakasih belum buat tahun aku banyak ajar lama aku isolasi alias hibernasi dan sekarang sambut penuh gembira semangat baru juang tuju baik masa yang baik tuhan  bandung tahunbaru
maklumaninfo khidmat perpustidakaan umskal tahun tahunbaru perpustidakaanumskal
dukung asta cita presiden prabowopolsek tptm gelar suluh anti narkoba smpn tanah putih tanjung lawan salampresisi polisiindonesia antinarkoba tahunbaru fyp jangkauanluas semuaorang sorot
electrizendimulai langkah kecil nyala ubah energi baru saat siap songsong masa depan semangat lanjut selamat tahun baru  pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
jenguk warga cibingbin blok wage rumah bakar peduliumatmelayanirakyat pkbisaolusibangsa tahunbaru cakiminow hasanuddinwahid jazilulfawaid real syaifulhooda hanifdhakiri cucunsyamsurijal idafauziyahnu halimiskandarnu ajam acep jamaludin dpp pkb
jalan ulurujangan lupa payung abu-abuselamat sambut tahun barusemoga semua sukses selaluselamat tahun baru salam diplomasi inidiplomasi indonesiainperth tahunbaru wrapped kjriprestasi
electrizen hidup awal buah mimpi selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
electrizen hidup awal buah mimpi selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
tambah pasu mu goto klik link nya sekarang link california trump jisoo lingormxsmootheendsitall slot kamis pagi viral viralvideo viralvideos indonesia tahunbaru
tim manajemen marcapada brilian ucap selamat tahun baru kalian semua moga tahun jadi tahun penuh semangat ceria tentu penuh sempat wujud cita kalian tahunbaru semangatbaru meraihcitacita marcapadabrilian
yayasanpahang januari antan - majlis amanat tahun baru yp kumpul yh dato indera mahmud mohd nawawi ketua pegawai eksekutif yayasan pahang ypu yayasanpahang amanat tahunbaru
januari antan - majlis amanat tahun baru yp kumpul yh dato indera mahmud mohd nawawi ketua pegawai eksekutif yayasan pahang ypu yayasanpahang amanat tahunbaru
jom tengok packing al-quran an naim ukir nama lt pustidakadaruliman tahunbaru hantarantunang alquranukirannama
tahun lalu resolusi realisasi abisaen dulu tenang yuk set ulang goals kamu tahun  tahunbaru newyear tahunbaru resolusitahunbaru jelajailokalsoloraya aglonesia kadinsurakarta
selamat tahun baru sahabatfrekuensi  balai monitor spektrum frekuensi siap dukung konektivitas komunikasi aman lancar sesuai regulasi indonesia maju tahun baru tahunbaru recap frekuensisatukannegeri komdigi
adik ipar juga sangat - azza karumaaku punya orang adik ipar nama fatoni umur finansial kira sudah layak sangat namun nyata shintaeyongdipecat novelrekomend ceritadewasa novelcore tahunbaru fiksi
aku kamu tahunbaru hotelsantikabanyuwangi libur jalanjalan jawat pulaumerah akudankamu separuhnafas
tugas parkir gaco raup omset kotor hingga rp juta lama libur tahun baru libur gaco tahunbaru tahunbaru kabarterdepan
moga tahun baru banyak bawa berkah bahagia kita semua  tahunbaru
ajar strategi pasar digital jangkau konsumen lebih luas efektif daftar sekarang digital digitalassets businesstips trainingtogether latih tahunbaru tahunbaru bcstrategy marketingsuccess
temu medan - bimoli klasik pouch minyak goreng  ml pcs blibli diskon  harga jadi rp coba buka link-nya deh blibli tahunbaru minyakgoreng viralterbaru voucher
lebih sehat amp cantikhi guardian angels dia biasa ingin mingu laku hidup lebih sehat amp cantik kalo kamu mau mulai biasa baik apa nih comment bawah yuk resolusi tahunbaru serudiguardian
hifriends apa kabar nih hari senin pertama tahun  makin seru rasa haru udah ganti tahun baru ceritain himin dong kolom komentar indosathifi tahunbaru berasakoneksinya
mengapa hari esok baik sja bangga pd diri sdiriyg lama mau tahan dg gaduh fikiran yg sengaja km laku philosogi of overthinking tahunbaruke enam
tahun baru promo baru nikmat free putien seaweed mini shrimps putien puri indah mall cuma laku - januari  yuk jangan lewat fujian specialty bikin nagih cek info sekarang promoputien tahunbaru seafoodlovers
 selamat tahun baru   kita sambut tahun dengan semangat baru capai mandiri finansial waktu rencana investasi wujud impi finansial kemandirianfinansial tahunbaru goals finansialcerdas
awal tahun baru energi maksimal dynex solusi baik forklift bisnis anda tahunbaru fyppp baterai bateraiforklift bpsi viral
aiptu nana ajar qur an warga jambi saling bantu baik salampresisi polisiindonesia poldariau tahunbaru fyp jangkauanluas semuaorang sorot
aiptu gusti polisi tari ajar seni klungkung bal salampresisi polisiindonesia poldariau tahunbaru fyp jangkauanluas semuaorang sorot
awal tahun awal tragedi milu serang brutal kamp ungsi jabalia gaza utara tewas luka banyak anak dosa rabu mereka hilang rumah keluarga harap fyp viralvideos newyear tahunbaru trending
salam sobatkristenapel perdana semangat baru langkah sama hari senin januari ditjen bimas kristen mulai jalan tahun baru penuh semangat komitmen lalu apel perdana kemenag bimaskristen semangatbarulangkahbersama tahunbaru
tahun hasil lewat juang sama moga tahun jadi langkah baru semangat jalan luar biasa pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru plnsiaganataru
electrizen hidup awal buah mimpi bawa yakin raih buah tuju selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
kece sedia bahan pokok butuh masyarakat kesetabilan harga bahan pokok lama raya natal tahun baru poldajateng polrestapati tahunbaru ekspresikandengancapcut capcut
makin depan youtube tukangsampahberdasi tahunbaru tahunbaru kranji kranjibekasi bekas bekasihits bekasibarat bekasiinfo laundry laundrykiloan cucikiloan loundrykiloan loundrysepatu sepatu selimut sprei sepatuoriginal kreatif cucisepatujakarta
januari pemuda jayasakti gelar syukur amp doa sama ketua knpi mesuji hadir semarak sama tahunbaru pemudabersatu knpimesuji
makin depan youtube tukangsampahberdasi tahunbaru tahunbaru kranji kranjibekasi bekas bekasihits bekasibarat bekasiinfo laundry laundrykiloan cucikiloan loundrykiloan loundrysepatu sepatu selimut sprei sepatuoriginal
azam tahun baru uqafy fyp ustazah ustazahqurrotulaien fyp ustazahqurrotulaienfatahyasin azam tahunbaru tahunbaru longervideos livehighlights tiktoklive live
himakiuny himaki himakiabirama tahunbaru
new douyin makeup transformation trend amazing tutorial douyin makeup beauty tiktoker trend tahunbaru transformation
powernet hadir event turnamen gacor tahun baru  langsung mulai januari s d januari total hadiah besar  promosi sekarang klik link bio powernet tahunbaru
ahok anies akrab tahun baru amat jadi dukung kuat pramono-rano beritanasional minggu ahok aniesbaswedan tahunbaru pramonoanung ranokarno gubernurdkijakarta
pernah gk teman rasa seru atas perahu kayak gin tahunbaru pantaiwaemarassatarmesebaratmanggarainttindonesia
kab tegal - jateng  rabu giat pmi kab tegal pam natal tahun baru nataru lokasi pos sehat rest area a taruk adiwerna pos obyek wisata guci pmiselalubantu pamnataru tahunbaru pmikabtegal
 bak kata orang new year new me lawak kampus gs store kadokawagempakstarz gempakstarz kgs lawakkampus lawakkampus keith selamattahunbaru tahunbaru tahun
kadang miris lihat lansia cari nafkah tidak kuat pas usia muda lihat sudah kurang tahunbaru
jadwal film spesial tahun baru transtv trans hari minggu januari film tahunbaru
berita minggu pagi peran polisi jombang jaga aman tertib lama natal tahun baru tempo hari dapat apresiasi ulama natal tahunbaru nataru polri polresjombang jombang ulama
selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
selamat tahun baru energi baru awal perubahandan semangat lanjut pln plnuntukindonesia acceleratingrenewableenergy swasembadaenergi tahunbaru
episode baru ruang cakap sekian purnama akhir update jugaak hihi yu denger saran kritik bangun sekali loh komunitaspodcaster podcaster tahunbaru podcast
kemendagri selamat tahun baru mari kobar semangat baru wujud indonesia maju tahunbaru kemendagri infokemendagri
kemendagri selamat tahun baru mari kobar semangat baru wujud indonesia maju kemendagri ri w risaldi titoka tahunbaru kemendagri infokemendagri
slot mania pragmatic play kalender event januari - januari total hadiah - dewatogel pragmaticplay turnamen ekslusif slotmania vip februari tahunbaru januari
koalisi ojol nasional apresiasi polri atas aman natal tahun baru sukses apresiasi polri natal tahunbaru aman koalisiojol
nu man fauzi apresiasi polri atas aman natal tahun baru aman damai apresiasi polri natal tahunbaru amandamai
semua wujud kerja sama sinergitas ada moga semua selalu beri sehat berkah selamat natal tahun baru tuhan kati semua aamiin padahariini natal tahunbaru gitj polrestapati
selamat tahun baru nikmat suara merdu nande tigan mey permata br tarigan lagu karo baik nyanyi hits bakat selalu hasil sentuh hati dengar  nandetigan meypermata lagukaro tahunbaru musiktradisional
heraloebisas masuk sel bisak ikut program dr kemen imipas biar kerja nya ga begal lg prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
blvberriis setor kemen imipas bukan kaleng nih prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
sobathebat kira kira harap kamu tahun apa nih sharing yuk tahunbaru
sih ide nya bagus biar bekal waktu selesai hukum nya prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
sih kemen imipas prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
intinyadeh kemen imipas ga nanggung setor nya ih prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
ilhampid listyosigitp siap masuk penjara ikut program ya om prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
ankiiim listyosigitp divhumas polri klarifikasi kerja nyata kayak kemen imipas deh prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
heraloebisas ada aja mending baca berita aja deh gue prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
dhemit is back divhumas polri listyosigitp penjara siap ikut program nya kemen imipas pak prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
doktertifa baca berita aja dl bu lg rame jg nih capai kemen imipas prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
fmuchtaar totalpolitikcom nih kemen imipas prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
berlianidris klarifikasi nya kayak gin aja lgsg ksh bukti prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
adamsyahaha inget suasana bulan puasa waktu kecil dl prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
txtdrbekasi sih ini prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
folkshittmedia masukin penjara biar bisak ikut program ini wkwkwk prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
tonightshow net baca berita aja deh klo gue prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
kumpar ga habis fikri prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
txtdrimedia viral nih berita nya prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
semua wujud kerja sama sinergitas ada moga semua selalu beri sehat berkah selamat natal tahun baru tuhan kati semua aamiin padahariini natal tahunbaru gitj polrestapati
cobeh auto ikut program deh besok prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
tukangbedah nyimak aja lah prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
pak tri prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
sih ini prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
fverocious kemen imipas ga pernah lelah narikin uang banyak buat setor prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
murtadhaone bantu sm kemen imipas nih prabowo perintah kemen kesangatmpias negara kasnegara weekend libur tahunbaru tahunbaru
dalam asa mu sobat hahahamakanya main nya mallbet official dong biar wd terus  mallbet trending bonuswelcome bonus claim viral konten tiktok facebook ikut publik happynewyear tahunbaru bonus
late posttugas organis misa tahun baru  januari lagu mulia madah bakti no koor lingkung yan smith amp sta bernadeta dirigen andy nong tahunbaru madahbakti pelayananliturgi mulia liturgikoor
late posttugas organis misa tahun baru  januari lagu tuhan kasihan madah bakti no koor lingkung smith amp sta bernadeta dirigen andy nong tahunbaru madahbakti tuhankasihanilah pelayananliturgi
tampil mulan jamela awal tahun mulanjameela mulanjameela malamtahunbaru tahunbaru
tampil nadin amizah urup cakecaine nadinamizah urup malamtahunbaru tahunbaru
yang susah mau screenshot laptop ikutin cara pasti hasil apa laptop semua bisa video tahunbaru tutorial toponechannels tweeter indonesia ssdf laptopfromhell a
manager humas daop madiun kuswardojo jelas puncak arus balik jadi januari  tumpang jatimnow arusbalik tahunbaru kaidaop madiun
tahunbaru rabu -- tgokwayangceritahantuindonesia dengananakmurid permulaanbaruyggembira teachersayangsofea
moga tahun semua jadi lebih baik aamiin  tahunbaru newyear